//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRepository.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public System.Guid id { get; set; }
        public string fullName { get; set; }
        public System.Guid classId { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public Nullable<System.DateTime> dateOut { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string address { get; set; }
        public System.Guid areaId { get; set; }
        public string fatherName { get; set; }
        public string fatherPhone { get; set; }
        public string motherName { get; set; }
        public string motherPhone { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Class Class { get; set; }
    }
}
